version: "3.9"

volumes:
  db-data: {}
  backend-ignore: {}
  client-ignore: {}

networks:
  coris:

services:
  db:
    container_name: mongodb
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "12345"
    volumes:
      - db-data:/data/db
    ports:
      - 27017:27017
    networks:
      - coris

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: coris-backend
    container_name: coris-backend
    restart: unless-stopped
    environment:
      MONGOOSE_URL: mongodb://admin:12345@db:27017
      COSMOS_REST: https://cosmos.api.ping.pub
      COSMOS_RPC_API: https://rpc.cosmos.network
      UMEE_REST_API: https://cosmos.api.ping.pub
      UMEE_RPC_API: https://rpc.cosmos.network
      PORT: 5000
    command: npm run dev
    depends_on:
      - db
    volumes:
      - ./backend:/usr/app/backend
      - backend-ignore:/usr/app/backend/node_modules
    expose:
      - "5000"
    ports:
      - "5000:5000"
    networks:
      - coris

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: coris-client
    container_name: coris-client
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_Cosmos_API: http://localhost:5000/umee
      NEXT_PUBLIC_UMEE_API: http://localhost:5000/umee
      NEXT_PUBLIC_COIN_ID: umee
    volumes:
      - ./client:/usr/app/client
      - client-ignore:/usr/app/client/node_modules
    expose:
      - "3000"
    ports:
      - "3000:3000"
    command: npm run dev
    depends_on:
      - db
      - backend
    networks:
      - coris

  adminer:
    profiles: ["adminer"]
    container_name: local_adminer
    image: adminer
    restart: unless-stopped
    environment:
      ADMINER_DESIGN: dracula
    ports:
      - 3333:8080
    depends_on:
      - db
    networks:
      - coris


