version: "3.9"

volumes:
  db-data: {}
  backend-ignore: {}
  client-ignore: {}

networks:
  coris:

services:
  db:
    container_name: mongodb
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "12345"
    volumes:
      - db-data:/data/db
    ports:
      - 27017:27017
    networks:
      - coris

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: coris-backend
    container_name: coris-backend
    restart: unless-stopped
    environment:
      MONGOOSE_URL: mongodb://admin:12345@db:27017
      COSMOS_REST: https://api.aphrodite.main.network.umee.cc
      PORT: 5100
    depends_on:
      - db
    volumes:
      - ./backend:/usr/app/backend
      - backend-ignore:/usr/app/backend/node_modules
    expose:
      - "5100"
    ports:
      - "5100:5100"
    # command: npm run dev
    networks:
      - coris

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: coris-client
    container_name: coris-client
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_CosmosChain_RESTAPI: https://api.aphrodite.main.network.umee.cc
      NEXT_PUBLIC_GetBlocksLatest: http://backend:5100/blocks/latest
      NEXT_PUBLIC_GetBlocks: http://backend:5100/blocks
    volumes:
      - ./client:/usr/app/client
      - client-ignore:/usr/app/client/node_modules
    expose:
      - "3000"
    ports:
      - "3000:3000"
    # command: npm run dev
    depends_on:
      - db
      - backend
    networks:
      - coris

  adminer:
    profiles: ["adminer"]
    container_name: local_adminer
    image: adminer
    restart: unless-stopped
    environment:
      ADMINER_DESIGN: dracula
    ports:
      - 3333:8080
    depends_on:
      - db
    networks:
      - coris
