version: "3.9"

volumes:
  db-data: {}
  redis-data: {}
  backend-ignore: {}
  client-ignore: {}

networks:
  coris:

services:
  db:
    container_name: mongodb
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "12345"
    volumes:
      - db-data:/data/db
    ports:
      - 27017:27017
    networks:
      - coris

  redis:
    container_name: redis
    image: redis:6.2.5-alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data/redis
    expose:
      - "6379"
    ports:
      - "6379:6379"
    networks:
      - coris 
    command: redis-server --bind 0.0.0.0 --port 6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: coris-backend
    container_name: coris-backend
    restart: unless-stopped
    environment:
     MONGOOSE_URL: mongodb://admin:12345@db:27017
     COSMOS_REST_API: https://api-cosmoshub-ia.cosmosia.notional.ventures
     COSMOS_RPC_API: https://rpc.cosmos.network
     AGORIC_REST_API: https://api-agoric.nodes.guru
     AGORIC_RPC_API: https://main.rpc.agoric.net:443
     AKASH_REST_API: https://api-akash-ia.cosmosia.notional.ventures
     AKASH_RPC_API: https://rpc-akash-ia.cosmosia.notional.ventures
     CRESCENT_REST_API: https://crescent-api.polkachu.com
     CRESCENT_RPC_API: https://mainnet.crescent.network:26657
     CHIHUAHUA_REST_API: https://chihuahua-api.polkachu.com
     CHIHUAHUA_RPC_API: https://chihuahua-rpc.polkachu.com:443
     NEUTRON_REST_API: https://neutron-api.polkachu.com
     NEUTRON_RPC_API: https://neutron-rpc.polkachu.com
     JUNO_REST_API: https://api-juno-ia.cosmosia.notional.ventures
     JUNO_RPC_API: https://rpc-juno-ia.cosmosia.notional.ventures:443
     STARGAZE_REST_API: https://stargaze-api.polkachu.com
     STARGAZE_RPC_API: https://stargaze-rpc.polkachu.com
     STRIDE_REST_API: https://stride-api.polkachu.com
     STRIDE_RPC_API: https://stride-rpc.polkachu.com:443
     IRISNET_REST_API: https://api.irishub-1.irisnet.org
     IRISNET_RPC_API: http://34.82.96.8:26657
     REGEN_REST_API: https://regen.stakesystems.io
     REGEN_RPC_API: https://regen.stakesystems.io:2053
     SIFCHAIN_REST_API: https://sifchain-api.polkachu.com
     SIFCHAIN_RPC_API: https://sifchain-rpc.polkachu.com:443
     OSMOSIS_REST_API: https://osmosis-api.polkachu.com
     OSMOSIS_RPC_API: https://osmosis-rpc.polkachu.com:443
     EVMOS_REST_API: https://evmos-api.polkachu.com
     EVMOS_RPC_API: https://evmos-rpc.polkachu.com:443
     CRYPTO_REST_API: https://rest.mainnet.crypto.org
     CRYPTO_RPC_API: https://rpc.mainnet.crypto.org:443
     BAND_REST_API: https://laozi1.bandchain.org/api
     BAND_RPC_API: http://rpc.laozi1.bandchain.org:80
     BEEZEE_REST_API: https://rest.getbze.com
     BEEZEE_RPC_API: https://rpc-1.getbze.com:443
     CANTO_REST_API: https://canto-api.polkachu.com
     CANTO_RPC_API: https://canto-rpc.polkachu.com:443
     CRONOS_REST_API: https://rest.cronos.org
     CRONOS_RPC_API: https://rpc.cronos.org:443
     DESMOS_REST_API: https://api.mainnet.desmos.network
     DESMOS_RPC_API: https://rpc.mainnet.desmos.network:443
     EMONEY_REST_API: https://emoney.validator.network/api
     EMONEY_RPC_API: https://emoney.validator.network:443
     MEME_REST_API: https://meme-api.polkachu.com:443
     MEME_RPC_API: https://meme-rpc.polkachu.com:443
     MUN_REST_API: https://mainnet1.mun.money
     MUN_RPC_API: https://mainnet1rpc.mun.money
     TENET_REST_API: https://tenet-api.lavenderfive.com
     TENET_RPC_API: https://tenet-rpc.lavenderfive.com
     PORT: 5001
     REDIS_HOST: redis
     REDIS_PORT: 6379
    command: npm run dev
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/usr/app/backend
      - backend-ignore:/usr/app/backend/node_modules
    expose:
      - "5001"
    ports:
      - "5001:5001"
    networks:
      - coris

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: coris-client
    container_name: coris-client
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_COSMOS_API: http://localhost:5001/cosmos
      NEXT_PUBLIC_AGORIC_API: http://localhost:5001/agoric
      NEXT_PUBLIC_AKASH_API: http://localhost:5001/akash
      NEXT_PUBLIC_CRESCENT_API: http://localhost:5001/crescent
      NEXT_PUBLIC_CHIHUAHUA_API: http://localhost:5001/chihuahua
      NEXT_PUBLIC_JUNO_API: http://localhost:5001/juno
      NEXT_PUBLIC_STARGAZE_API: http://localhost:5001/stargaze  
    volumes:
      - ./client:/usr/app/client
      - client-ignore:/usr/app/client/node_modules
    expose:
      - "3000"
    ports:
      - "3000:3000"
    command: npm run dev
    depends_on:
      - db
      - backend
      - redis
    networks:
      - coris

  adminer:
    profiles: ["adminer"]
    container_name: local_adminer
    image: adminer
    restart: unless-stopped
    environment:
      ADMINER_DESIGN: dracula
    ports:
      - 3333:8080
    depends_on:
      - db
    networks:
      - coris
