name: Client Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  client-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Run client linter
        run: npm run lint
